opt_in_rules:
- empty_count
- empty_string

disabled_rules:
- trailing_comma
- large_tuple
- todo

excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib

force_cast:
  warning

identifier_name:
  min_length:
    warning: 1
    error: 0
  max_length: 40

line_length:
  warning: 160
  error: 200
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

vertical_whitespace:
  max_empty_lines: 2

function_body_length:
  warning: 300
  error: 500

function_parameter_count:
  warning: 6
  error: 8

type_body_length:
  warning: 600
  error: 800

file_length:
  warning: 1000
  error: 1500
  ignore_comment_only_lines: true

cyclomatic_complexity:
  warning: 20
  error: 25

reporter: "xcode"
